kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: stock-data-provider
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stock-data-provider
    spec:
      containers:
        - name: stock-data-provider
          image: anandanand84/stock-data-provider
          volumeMounts:
            - name: certs
              mountPath: /certs
          env:
            - name: ENVIRONMENT
              value: "PROD"
          ports:
            - containerPort: 30443
          resources:
            limits:
              cpu: 300m
              memory: 0.5Gi
            requests:
              cpu: 250m
              memory: 0.4Gi
      volumes:
        - name: certs
          secret:
            secretName: certs